project:
  type: website
  output-dir: docs

website:
  title: "E21 Computer Engineering Fundamentals"
  navbar:
    right:
      - href: "https://moodle.swarthmore.edu/course/view.php?id=30092"
        text: Moodle
      - href: "https://www.gradescope.com/courses/1232975"
        text: Gradescope
      - href: "https://edstem.org/us/courses/94270/discussion"
        text: Ed Discussion
    left:
      - href: index.qmd
        text: Homepage
  search:
    location: navbar
    type: overlay
  sidebar:
    style: docked
    collapse-level: 2
    contents:
      - href: syllabus.qmd
      - href: about.qmd
      - section: "Academic Support"
        contents: "AcademicSupport/**"
      - href: "Labs/index.qmd"
      - section: "Lecture"
        contents: "Lectures/**"
        sort: "order"
      - section: "Homework"
        contents: "Homework/**"
        sort: "order"


format:
  html:
    highlight-style: github
    theme:
      - brand
    toc: true
    format-links:
      - format: revealjs
        text: "Slideshow"
      - format: pdf
        text: "PDF"
